### ISSUE TITLE
Using .NetFramework throw Unable to read data from the transport connection: The connection was closed.

### ISSUE THREAD

**Issue by fengyuan213** [bezzad/Downloader#2]
Hello. I can't download a file normally using ur package in .Net Framework environment
![image](https://user-images.githubusercontent.com/26819159/82121571-b7b79c00-97c0-11ea-8eee-f0d3cccb3db4.png)
However, If I use the sample you provided, I tested sooo many times and it just work fine with no problem at all.
I did a google search to try to find some relavent problem.
Here is what I can find: https://social.msdn.microsoft.com/Forums/en-US/c620ce2c-c512-4c9f-a481-521ecd260039/systemioioexception-unable-to-read-data-from-the-transport-connection-the-connection-was-closed?forum=vstswebtest
Please kindly look and try to fix this issue
Finally My configuration:

```csharp
private async void DownloadClientAsync
{
           var chunkCount =8;
            var downloadOpt = new DownloadConfiguration()
            {

                ParallelDownload = true, // download parts of file as parallel or not
                BufferBlockSize = 8000, // usually, hosts support max to 8000 bytes
                ChunkCount = chunkCount, // file parts to download
                MaxTryAgainOnFailover = int.MaxValue, // the maximum number of times to fail.
                OnTheFlyDownload = true, // caching in-memory mode
                Timeout = 3000 // timeout (millisecond) per stream block reader
            };
            var ds = new DownloadService(downloadOpt);
            ds.ChunkDownloadProgressChanged += OnChunkDownloadProgressChanged;
            ds.DownloadProgressChanged += OnDownloadProgressChanged;
            ds.DownloadFileCompleted += OnDownloadFileCompleted;

            var url = "http://resources.downloads.pokecity.club/2020.rar";
            System.Net.ServicePointManager.Expect100Continue = false;
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
            var fileName = Path.Combine(Path.GetTempPath(), "downloadtext.rar");
            await ds.DownloadFileAsync(url, fileName).ConfigureAwait(false);
            ds.Clear();
}

private void OnDownloadProgressChanged(object sender, DownloadProgressChangedEventArgs e)
{
            var nonZeroSpeed = e.BytesPerSecondSpeed == 0 ? 0.0001 : e.BytesPerSecondSpeed;
            var estimateTime = (int)((e.TotalBytesToReceive - e.BytesReceived) / nonZeroSpeed);
            var isMins = estimateTime >= 60;
            var timeLeftUnit = "秒";
            if (isMins)
            {
                timeLeftUnit = "分钟";
                estimateTime /= 60;
            }
           
            //flowLayoutPanel1.Controls.Add();
            
            var a= $"{e.ProgressPercentage:N3}%  -  {CalcMemoryMensurableUnit(e.BytesPerSecondSpeed)}/s  -  " +
                            $"[{CalcMemoryMensurableUnit(e.BytesReceived)} of {CalcMemoryMensurableUnit(e.TotalBytesToReceive)}], {estimateTime} {timeLeftUnit} left";
            Console.Title=a;
            //DownloadingProgressBar.Value= ((int)(e.ProgressPercentage * 100));

}
```

**Comment by bezzad** [comment]
Hi @fengyuan213,

Thanks for reporting the issue. 
I check your download URL and sample, but that's work correctly and I can download your files successfully! Of course, this link has some server-side problems such as disconnecting some times and I tested by some downloaders like IDM and all of them have this problem when downloading from.

And I check [this link](https://social.msdn.microsoft.com/Forums/en-US/c620ce2c-c512-4c9f-a481-521ecd260039/systemioioexception-unable-to-read-data-from-the-transport-connection-the-connection-was-closed?forum=vstswebtest) and our project works exactly with the `ReadAsync` command instead of the `ReadToEnd`, But I change some request options to improve the stability and after the test I released a new version.

**Comment by bezzad** [comment]
@fengyuan213 I released a new version 1.0.9, please test that.

**Comment by fengyuan213** [comment]
Hello, I tested with the new version again just now. .The good news is that It can download succeed sometimes with parallel downloads option changed to false, however, When I try to download the file in parallel. Then it throws the same error at the download chunks method. However, I don't really think there is any server-side issues because the link I use to test download is from a known CDN network provider so... I checked with my link through IDM multi-thread downloading and it just works perfectly without any pieces of the issue. I have no idea why that is happening. Maybe it an idea to automatically retry to download the same chunk data if this exception occurred to try to avoid the issue. 
![image](https://user-images.githubusercontent.com/26819159/82135975-64366400-983b-11ea-9eec-a7d935efd53b.png)


Also, downloading sometimes stack. From the title bar of the console, it is able to see it's on 29.671% progress of downloading. The things are the progress never gets changed even for half an hour. Maybe regularly check if the download thread still alive...
![image](https://user-images.githubusercontent.com/26819159/82136124-d52a4b80-983c-11ea-9604-b9ef0074d520.png)


Please help

**Comment by fengyuan213** [comment]
Update, the  ParallelDownload = false option could let me download successful but it only for some time. There is a chance like 1/3 download failed and thows same exception as before. See picture belovw
![image](https://user-images.githubusercontent.com/26819159/82136311-0c99f780-983f-11ea-9333-13e9b2594fd3.png)

**Comment by fengyuan213** [comment]
By the way, I am using WinForm in the Console Application by setting STAThread Attribute. Is that the case?

**Comment by bezzad** [comment]
@fengyuan213 No, your application is fine and no problem. My downloader library has no dependency on your or any other project.
In this case, I have to work harder to find out why. If you have any information about this problem, be sure to mention it here.
Thanks

**Comment by fengyuan213** [comment]
Ok , Please update the version so I can test it.

**Comment by fengyuan213** [comment]
Today, I had another download issue with the same error message : Unable to read data from the transport connection: the connection was closed
![image](https://user-images.githubusercontent.com/26819159/82212423-1f96ef80-9945-11ea-9829-84ce037bd738.png)

The Client Instance hasn't disposed of it when downloading data.
It is very strange in this case because this function was worked perfectly.....The network section seems to be less stability when I changed the project to STAThread....

**Comment by fengyuan213** [comment]
Hello there, I have a super super good news, After I testing between net core and framework for lots of time. I figured it out why. The solution is so simple. When downloading chunkes, the downloader catches webexception and  the following. 
 e.Source == "System.Net.Http" ||
 e.Source == "System.Net.Sockets" ||
e.Source == "System.Net.Security" ||
 e.InnerException is SocketException)
In the Framework I don't know how but "Unable to read data from the transport connection " is a part of IOException Instead of any of them above. Simplify just append  "e is IOException" and problem solved. Please share your throughts becuase I am not too sure if it is a good way but it solved my problem.

**Comment by fengyuan213** [comment]
![image](https://user-images.githubusercontent.com/26819159/84563793-a5fdf000-ad90-11ea-8172-60cdcf965973.png)

**Comment by fengyuan213** [comment]
Also, The CacheInMemory =False mode is not working which means all downloads are forced to cacheinmemory

**Comment by bezzad** [comment]
@fengyuan213 Thank you for your follow-up. I have made changes to the source that I hope will solve your problems. You can see these changes in version 1.2.

**Comment by bezzad** [comment]
New version (1.2) released. Please test with that to sure solved this issue or not.
The caching mode also fixed in this version.

**Comment by bezzad** [comment]
@fengyuan213 have you tested this issue in the new version?

**Comment by fengyuan213** [comment]
Hello,
I tested the new version today. It is great to have a new feature like speed limit. However, the problem still exist...... 
![image](https://user-images.githubusercontent.com/26819159/85913882-46f9aa00-b86b-11ea-8642-35eb5ee5228f.png)

**Comment by fengyuan213** [comment]
Hello, I think it is kinds of useful update...The post above uses Downloader.Sample's default configuration with KeepAlive=false
The error below occurs when I set to the KeepAlive opt = true.
Configuration:
![image](https://user-images.githubusercontent.com/26819159/85914168-8d500880-b86d-11ea-9145-69181754b8b7.png)

Stacktrace:
"   at System.IO.Stream.BeginReadInternal(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state, Boolean serializeAsynchronously)\r\n   at System.IO.Stream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)\r\n   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)\r\n   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)\r\n   at Downloader.DownloadService.<ReadStreamOnTheFly>d__45.MoveNext() in C:\\Users\\Fengyuan\\source\\repos\\Downloader\\src\\Downloader\\DownloadService.cs:line 285\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Downloader.DownloadService.<DownloadChunk>d__44.MoveNext() in C:\\Users\\Fengyuan\\source\\repos\\Downloader\\src\\Downloader\\DownloadService.cs:line 228"
![image](https://user-images.githubusercontent.com/26819159/85914102-ec614d80-b86c-11ea-97fc-0348d404dce5.png)

**Comment by bezzad** [comment]
@fengyuan213  some servers does not support KeepAlive=true option, so I set default value to false.
In the first error, every time I check that, I could see no error! Is this the download link?
‍‍`"http://resources.downloads.pokecity.club/2020.rar"`

**Comment by fengyuan213** [comment]
Yep......

**Comment by fengyuan213** [comment]
The link above u might not able to download in your area.. try this one:
http://test.download.pokecity.club/2020.rar

**Comment by bezzad** [comment]
@fengyuan213  I released the new version v1.5.0. Please check this version. And if you have still this problem, please send me a complete exception data as `TEXT` or `JSON` to check exception source and types. 
Thanks

**Comment by bezzad** [comment]
@fengyuan213 Was this problem solved with the new version?
